# Copyright (c) 2025 Nurol, Inc. (nurol.ai)
# This file is licensed under the Creative Commons Attribution-NonCommercial 4.0 International License (CC BY-NC 4.0).
# For commercial use, please contact info@nurol.ai

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nurops-event-manager
  namespace: kube-system
  annotations:
    helm.cattle.io/chart-url: https://nurol-ai.github.io/charts/nurops-event-manager-0.1.0.tgz
    helm.cattle.io/chart-version: "0.1.0"
spec:
  repo: https://nurol-ai.github.io/charts
  chart: nurops-event-manager
  version: "0.1.0"
  targetNamespace: monitoring
  valuesContent: |-
    eventManager:
      enabled: true
      deployment:
        replicas: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      image:
        repository: nurops/nurops-event-manager
        tag: "latest"
        pullPolicy: IfNotPresent
      # Environment variables - matching container implementation
      env:
        - name: SERVER_PORT
          value: "8082"
        - name: HOST
          value: "0.0.0.0"
        - name: DATABASE_PATH
          value: "/data/event_history.db"
        - name: HISTORY_RETENTION_DAYS
          value: "30"
        - name: CLEANUP_INTERVAL_SECONDS
          value: "3600"
        - name: CORS_ORIGINS
          value: "*"
      service:
        type: ClusterIP
        port: 80
        targetPort: 80
      persistence:
        enabled: true
        storageClass: "local-path"
        size: 1Gi
        accessModes:
          - ReadWriteOnce
        mountPath: "/data"
      serviceAccount:
        create: true
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/health"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nurops-event-manager
              topologyKey: kubernetes.io/hostname
---
# Alternative: Using HelmChartConfig for more advanced configuration
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: nurops-event-manager-config
  namespace: kube-system
spec:
  valuesContent: |-
    # Global configuration
    global:
      namespaceOverride: "monitoring"
    
    # NurOps Event Manager specific overrides
    eventManager:
      # Enable high availability mode
      deployment:
        replicas: 3
      
      # Use specific image version
      image:
        repository: nurops/nurops-event-manager
        tag: "latest"
      
      # Environment variables for production - matching container implementation
      env:
        - name: SERVER_PORT
          value: "8082"
        - name: HOST
          value: "0.0.0.0"
        - name: DATABASE_PATH
          value: "/data/event_history.db"
        - name: HISTORY_RETENTION_DAYS
          value: "90"
        - name: CLEANUP_INTERVAL_SECONDS
          value: "3600"
        - name: CORS_ORIGINS
          value: "*"
      
      # Configure persistence for production
      persistence:
        enabled: true
        storageClass: "local-path"
        size: 5Gi
        accessModes:
          - ReadWriteOnce
        mountPath: "/data"
        annotations:
          backup.velero.io/backup-volumes: "data"
          velero.io/exclude-from-backup: "false"
      
      # Configure for production
      service:
        type: LoadBalancer
        port: 80
        targetPort: 80
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
          service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      
      # Resource limits for production
      deployment:
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
      
      # Security hardening
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      
      # Pod security context
      podSecurityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      
      # Network policies
      podAnnotations:
        vpc.amazonaws.com/pod-eni: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/health"
      
      # Node placement
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
        kubernetes.io/os: linux
      
      # Tolerations for dedicated nodes
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "nurops-event-manager"
          effect: "NoSchedule"
      
      # Pod affinity for high availability
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                                  - nurops-event-manager
            topologyKey: kubernetes.io/hostname
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nurops-event-manager
              topologyKey: topology.kubernetes.io/zone
