# Copyright (c) 2025 Nurol, Inc. (nurol.ai)
# This file is licensed under the Creative Commons Attribution-NonCommercial 4.0 International License (CC BY-NC 4.0).
# For commercial use, please contact info@nurol.ai

# Default values for NurOps Event Manager
# This is a YAML-formatted file.

# Global configuration
global:
  # Override the namespace where resources are deployed
  # If not set, will use the release namespace
  namespaceOverride: ""

# NurOps Event Manager configuration
eventManager:
  enabled: true
  
  # Deployment configuration
  deployment:
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
  
  # Container image configuration
  image:
    repository: nurops/nurops-event-manager
    tag: "latest"
    pullPolicy: IfNotPresent
    # Optional: specify image pull secrets
    pullSecrets: []
    # - name: regcred
  
  # Environment variables - matching the container implementation
  env:
    # Single port for both HTTP and WebSocket connections
    - name: SERVER_PORT
      value: "8082"
    - name: HOST
      value: "0.0.0.0"
    # Database configuration
    - name: DATABASE_PATH
      value: "/data/event_history.db"
    # Data retention configuration
    - name: HISTORY_RETENTION_DAYS
      value: "30"
    - name: CLEANUP_INTERVAL_SECONDS
      value: "3600"
    # CORS configuration
    - name: CORS_ORIGINS
      value: "*"
  
  # Service configuration
  service:
    type: ClusterIP
    port: 8082
    targetPort: 8082
  
  # Health check configuration
  livenessProbe:
    httpGet:
      path: /health
      port: 8082
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /ready
      port: 8082
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  # Service account configuration
  serviceAccount:
    create: true
    name: ""
    annotations: {}
  
  # Pod annotations
  podAnnotations: {}
  
  # Pod security context
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  
  # Container security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  
  # Node selector
  nodeSelector: {}
  
  # Tolerations
  tolerations: []
  
  # Affinity
  affinity: {}
  
  # Persistence configuration for SQLite3 database
  persistence:
    enabled: true
    storageClass: "local-path"
    size: 1Gi
    accessModes:
      - ReadWriteOnce
    mountPath: /data
    annotations: {}
  
  # Network Policy
  networkPolicy:
    enabled: false
    ingress:
      # Allow traffic from monitoring namespace
      - namespaceSelector:
          matchLabels:
            name: monitoring
        ports:
          - protocol: TCP
            port: 8082
      # Allow traffic from kube-system namespace
      - namespaceSelector:
          matchLabels:
            name: kube-system
        ports:
          - protocol: TCP
            port: 8082
    egress:
      # Allow DNS queries
      - ports:
          - protocol: UDP
            port: 53
      # Allow HTTP/HTTPS traffic
      - ports:
          - protocol: TCP
            port: 80
          - protocol: TCP
            port: 443
  
  # Autoscaling configuration
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

# Override the name of the chart
nameOverride: ""

# Override the full name of the chart
fullnameOverride: ""
