{{- if .Values.storage.certs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nuros-reverse-proxy.fullname" . }}-certs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nuros-reverse-proxy.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.storage.certs.accessModes | nindent 4 }}
  {{- if .Values.storage.certs.storageClass }}
  storageClassName: {{ .Values.storage.certs.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.certs.size }}
{{- end }}

---
{{- if .Values.storage.logs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nuros-reverse-proxy.fullname" . }}-logs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nuros-reverse-proxy.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.storage.logs.accessModes | nindent 4 }}
  {{- if .Values.storage.logs.storageClass }}
  storageClassName: {{ .Values.storage.logs.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.logs.size }}
{{- end }}
